### ISSUE TITLE
目前TXT未收录的《通用规范汉字表》汉字

### ISSUE THREAD

**Issue by CNMan** [CNMan/XDHYCD7th#3]
|字表序号|Unicode编码|汉字|编码区|拼音|
|------|------|------|------|------|
|7642|U+8508|蔈|CJK|biāo|
|7141|U+688C|梌|CJK|chá|
|6783|U+8356|荖|CJK|chā|
|7082|U+5832|堲|CJK|cí|
|7244|U+60D4|惔|CJK|dàn|
|7062|U+6D5F|浟|CJK|dí|
|7978|U+5B25|嬥|CJK|diào|
|7272|U+5A60|婠|CJK|guàn|
|7175|U+5D21|崡|CJK|hán|
|8095|U+9FA2|龢|CJK|hé|
|6775|U+578E|垎|CJK|hè|
|7081|U+96BA|隺|CJK|hè|
|7721|U+7187|熇|CJK|hè|
|7290|U+583C|堼|CJK|hèng|
|6555|U+7392|玒|CJK|hóng|
|7552|U+8C3C|谼|CJK|hóng|
|6677|U+6608|昈|CJK|hù|
|7743|U+5AED|嫭|CJK|hù|
|7902|U+6FE9|濩|CJK|hù|
|6676|U+6612|昒|CJK|hū|
|7567|U+89DF|觟|CJK|huà|
|6836|U+5CD8|峘|CJK|huán|
|8003|U+956E|镮|CJK|huán|
|7451|U+5A93|媓|CJK|huáng|
|7467|U+745D|瑝|CJK|huáng|
|7049|U+70E0|烠|CJK|huí|
|7845|U+6A5E|橞|CJK|huì|
|7269|U+5A6B|婫|CJK|hùn|
|8066|U+7031|瀱|CJK|jì|
|6663|U+6785|枅|CJK|jī|
|6907|U+53DA|叚|CJK|jiǎ|
|7758|U+8503|蔃|CJK|jiàng|
|6899|U+6054|恔|CJK|jiǎo|
|7919|U+74AC|璬|CJK|jiǎo|
|7897|U+71CB|燋|CJK|jiāo|
|6631|U+5C8A|岊|CJK|jié|
|7067|U+6088|悈|CJK|jiè|
|7316|U+9111|鄑|CJK|jìn|
|7733|U+616C|慬|CJK|jìn|
|6936|U+73D2|珒|CJK|jīn|
|6745|U+8FF3|迳|CJK|jìng|
|7225|U+7AEB|竫|CJK|jìng|
|7832|U+74A5|璥|CJK|jǐng|
|6595|U+5CA0|岠|CJK|jù|
|6759|U+73C7|珇|CJK|jù|
|6683|U+5CA8|岨|CJK|jǔ|
|6969|U+7820|砠|CJK|jū|
|7174|U+5D0C|崌|CJK|jū|
|7263|U+5A35|娵|CJK|jū|
|7230|U+7106|焆|CJK|juān|
|8101|U+7383|玃|CJK|jué|
|7159|U+6659|晙|CJK|jùn|
|7314|U+8470|葰|CJK|jùn|
|6717|U+708C|炌|CJK|kài|
|7360|U+5D41|嵁|CJK|kān|
|6881|U+6D18|洘|CJK|kǎo|
|6877|U+70A3|炣|CJK|kě|
|6938|U+73E2|珢|CJK|kèn|
|7116|U+57EA|埪|CJK|kōng|
|7509|U+787F|硿|CJK|kōng|
|7044|U+7AD8|竘|CJK|kǒu|
|7582|U+7143|煃|CJK|kuǐ|
|6854|U+4FEB|俫|CJK|lái|
|7546|U+7B64|筤|CJK|láng|
|7488|U+84E2|蓢|CJK|lǎng|
|7846|U+6A51|橑|CJK|lǎo|
|7982|U+91D0|釐|CJK|lí|
|6528|U+6738|朸|CJK|lì|
|6939|U+73D5|珕|CJK|lì|
|7462|U+7453|瑓|CJK|liàn|
|7212|U+811F|脟|CJK|liè|
|7691|U+7B96|箖|CJK|lín|
|8022|U+7FF7|翷|CJK|lín|
|6654|U+577D|坽|CJK|líng|
|6743|U+59C8|姈|CJK|líng|
|6828|U+6624|昤|CJK|líng|
|7904|U+6FAA|澪|CJK|líng|
|7818|U+746C|瑬|CJK|liú|
|7867|U+7581|疁|CJK|liú|
|6762|U+73CB|珋|CJK|liǔ|
|7538|U+7A11|稑|CJK|lù|
|7615|U+52E0|勠|CJK|lù|
|7842|U+8557|蕗|CJK|lù|
|7568|U+2677C|𦝼|CJK-B|lǘ|
|6781|U+578F|垏|CJK|lǜ|
|6961|U+68A0|梠|CJK|lǚ|
|6808|U+5396|厖|CJK|máng|
|7501|U+6959|楙|CJK|mào|
|7472|U+7442|瑂|CJK|méi|
|7453|U+5A84|媄|CJK|měi|
|6906|U+7955|祕|CJK|mì|
|7507|U+7888|碈|CJK|mín|
|7354|U+27FF9|𧿹|CJK-B|mǔ|
|7303|U+8433|萳|CJK|nán|
|7447|U+5A7B|婻|CJK|nàn|
|7448|U+5A86|媆|CJK|nèn|
|7084|U+28E99|𨺙|CJK-B|nì|
|7977|U+5B2C|嬬|CJK|nòu|
|7191|U+7B2F|笯|CJK|nú|
|7026|U+8225|舥|CJK|pā|
|6719|U+6CD9|泙|CJK|pēng|
|6572|U+82C9|苉|CJK|pǐ|
|6758|U+73B6|玶|CJK|píng|
|6792|U+8353|荓|CJK|píng|
|7165|U+86B2|蚲|CJK|píng|
|7058|U+6D84|涄|CJK|pīng|
|7794|U+769B|皛|CJK|pò|
|7484|U+84B1|蒱|CJK|pú|
|7752|U+58A3|墣|CJK|pú|
|7948|U+7A59|穙|CJK|pú|
|6529|U+28678|𨙸|CJK-B|qí|
|7598|U+612D|愭|CJK|qí|
|6882|U+6D13|洓|CJK|qì|
|7852|U+78DC|磜|CJK|qì|
|6597|U+5447|呇|CJK|qǐ|
|7267|U+5A4D|婍|CJK|qǐ|
|7306|U+8474|葴|CJK|qián|
|6538|U+4F23|伣|CJK|qiàn|
|7485|U+84A8|蒨|CJK|qiàn|
|6523|U+5732|圲|CJK|qiān|
|6580|U+6744|杄|CJK|qiān|
|8071|U+5B45|孅|CJK|qiān|
|7504|U+7883|碃|CJK|qìng|
|8087|U+7048|灈|CJK|qú|
|6651|U+5765|坥|CJK|qū|
|7271|U+5A58|婘|CJK|quán|
|7468|U+7454|瑔|CJK|quán|
|4291|U+72E8|狨|CJK|róng|
|7981|U+74C0|瓀|CJK|ruǎn|
|7438|U+6E9E|溞|CJK|sāo|
|7589|U+6EB9|溹|CJK|sè|
|7917|U+74B1|璱|CJK|sè|
|7871|U+5DA6|嶦|CJK|shàn|
|7353|U+6671|晱|CJK|shǎn|
|7052|U+70FB|烻|CJK|shān|
|6765|U+73BF|玿|CJK|sháo|
|6803|U+67D6|柖|CJK|sháo|
|6674|U+6607|昇|CJK|shēng|
|6909|U+965E|陞|CJK|shēng|
|7449|U+5A9E|媞|CJK|shì|
|6650|U+90BF|邿|CJK|shī|
|7268|U+5A4C|婌|CJK|shú|
|7261|U+9683|隃|CJK|shù|
|7386|U+7A0C|稌|CJK|shǔ|
|6738|U+964E|陎|CJK|shū|
|7206|U+6086|悆|CJK|shū|
|4853|U+5530|唰|CJK|shuā|
|7555|U+8168|腨|CJK|shuàn|
|7170|U+5D27|崧|CJK|sōng|
|7313|U+8490|蒐|CJK|sōu|
|7392|U+5083|傃|CJK|sù|
|7335|U+7526|甦|CJK|sū|
|7833|U+74B2|璲|CJK|suì|
|7973|U+895A|襚|CJK|suì|
|8021|U+65DE|旞|CJK|suì|
|7985|U+97B3|鞳|CJK|tà|
|7920|U+74AE|璮|CJK|tǎn|
|6734|U+5F22|弢|CJK|tāo|
|7600|U+6146|慆|CJK|tāo|
|7463|U+7445|瑅|CJK|tí|
|7605|U+7994|禔|CJK|tí|
|6822|U+76F7|盷|CJK|tián|
|7352|U+666A|晪|CJK|tiǎn|
|6510|U+5722|圢|CJK|tǐng|
|7051|U+70F6|烶|CJK|tǐng|
|6835|U+54C3|哃|CJK|tóng|
|8020|U+2648D|𦒍|CJK-B|tóng|
|7409|U+732F|猯|CJK|tuān|
|7586|U+7153|煓|CJK|tuān|
|7955|U+9B4B|魋|CJK|tuí|
|7422|U+711E|焞|CJK|tuī|
|3580|U+8284|芄|CJK|wán|
|6635|U+59A7|妧|CJK|wàn|
|7332|U+6900|椀|CJK|wǎn|
|6502|U+5C22|尢|CJK|wāng|
|6583|U+5C2A|尪|CJK|wāng|
|6840|U+5CD7|峗|CJK|wéi|
|7286|U+741F|琟|CJK|wéi|
|7585|U+715F|煟|CJK|wèi|
|7975|U+87B1|螱|CJK|wèi|
|6619|U+6C87|沇|CJK|wěi|
|7838|U+85B3|薳|CJK|wěi|
|6575|U+82A0|芠|CJK|wén|
|8006|U+99A7|馧|CJK|wò|
|6998|U+5CFF|峿|CJK|wú|
|7100|U+73F8|珸|CJK|wú|
|6673|U+65FF|旿|CJK|wǔ|
|6857|U+4FD9|俙|CJK|xī|
|6874|U+997B|饻|CJK|xī|
|7859|U+66BF|暿|CJK|xī|
|7898|U+71BB|熻|CJK|xī|
|8059|U+9145|酅|CJK|xī|
|7157|U+7FC8|翈|CJK|xiá|
|6603|U+4F2D|伭|CJK|xián|
|6820|U+2AFA2|𪾢|CJK-C|xiàn|
|7607|U+7992|禒|CJK|xiǎn|
|6934|U+73E6|珦|CJK|xiàng|
|7054|U+6D8D|涍|CJK|xiào|
|7441|U+6569|敩|CJK|xiào|
|7192|U+5070|偰|CJK|xiè|
|8075|U+24AC9|𤫉|CJK-B|xiè|
|7464|U+7446|瑆|CJK|xīng|
|7584|U+714B|煋|CJK|xīng|
|6927|U+73DB|珛|CJK|xiù|
|6940|U+73DD|珝|CJK|xǔ|
|6988|U+5194|冔|CJK|xǔ|
|6589|U+65F4|旴|CJK|xū|
|6763|U+73B9|玹|CJK|xuán|
|7769|U+66B6|暶|CJK|xuán|
|7102|U+7404|琄|CJK|xuàn|
|7202|U+8852|衒|CJK|xuàn|
|6824|U+54BA|咺|CJK|xuān|
|7440|U+6103|愃|CJK|xuān|
|6929|U+740A|琊|CJK|yá|
|7108|U+5810|堐|CJK|yá|
|7858|U+8664|虤|CJK|yán|
|7429|U+6E30|渰|CJK|yǎn|
|7825|U+622D|戭|CJK|yǎn|
|7722|U+6F39|漹|CJK|yān|
|7229|U+7F95|羕|CJK|yàng|
|6678|U+5489|咉|CJK|yǎng|
|7595|U+6EE7|滧|CJK|yáo|
|7613|U+5AB1|媱|CJK|yáo|
|6666|U+678D|枍|CJK|yì|
|7570|U+88DB|裛|CJK|yì|
|6802|U+6810|栐|CJK|yǒng|
|7907|U+6FAD|澭|CJK|yōng|
|6905|U+7950|祐|CJK|yòu|
|7572|U+7600|瘀|CJK|yū|
|6548|U+6C4B|汋|CJK|yuè|
|8098|U+7C65|籥|CJK|yuè|
|7247|U+5BC1|寁|CJK|zǎn|
|7156|U+556B|啫|CJK|zé|
|7720|U+912B|鄫|CJK|zēng|
|7193|U+5061|偡|CJK|zhàn|
|7768|U+66B2|暲|CJK|zhāng|
|7294|U+5586|喆|CJK|zhé|
|6826|U+6623|昣|CJK|zhěn|
|7791|U+7A39|稹|CJK|zhěn|
|7621|U+7467|瑧|CJK|zhēn|
|6984|U+664A|晊|CJK|zhì|
|7522|U+8DF1|跱|CJK|zhì|
|6658|U+26B5C|𦭜|CJK-B|zhī|
|6788|U+833D|茽|CJK|zhòng|
|7025|U+822F|舯|CJK|zhōng|
|7679|U+953A|锺|CJK|zhōng|
|7270|U+5A64|婤|CJK|zhōu|
|6970|U+782B|砫|CJK|zhǔ|
|7696|U+50CE|僎|CJK|zhuàn|
|5760|U+50EE|僮|CJK|zhuàng|
|6746|U+53D5|叕|CJK|zhuó|
|7351|U+666B|晫|CJK|zhuó|
|7021|U+5027|倧|CJK|zōng|
|8033|U+9B37|鬷|CJK|zōng|
|7695|U+50D4|僔|CJK|zǔn|
|7777|U+5642|噂|CJK|zǔn|
|7783|U+5D9F|嶟|CJK|zūn|
|7944|U+28C54|𨱔|CJK-B|zūn|
|6551|U+2C8DE|𬣞|CJK-E|暂时未知|
|6594|U+2BD77|𫵷|CJK-E|暂时未知|
|6640|U+2B61C|𫘜|CJK-C|暂时未知|
|6657|U+48BC|䢼|CJK-A|暂时未知|
|6670|U+2CA02|𬨂|CJK-E|暂时未知|
|6686|U+37C3|㟃|CJK-A|暂时未知|
|6688|U+2CB29|𬬩|CJK-E|暂时未知|
|6700|U+344A|㑊|CJK-A|暂时未知|
|6730|U+2B363|𫍣|CJK-C|暂时未知|
|6731|U+2C8F3|𬣳|CJK-E|暂时未知|
|6739|U+2CBC0|𬯀|CJK-E|暂时未知|
|6744|U+2BC1B|𫰛|CJK-E|暂时未知|
|6747|U+2CCF5|𬳵|CJK-E|暂时未知|
|6752|U+2B80A|𫠊|CJK-D|暂时未知|
|6797|U+3B55|㭕|CJK-A|暂时未知|
|6847|U+2CB31|𬬱|CJK-E|暂时未知|
|6848|U+2CB2D|𬬭|CJK-E|暂时未知|
|6865|U+43E1|䏡|CJK-A|暂时未知|
|6867|U+26676|𦙶|CJK-B|暂时未知|
|6879|U+3DB2|㶲|CJK-A|暂时未知|
|6884|U+3CDA|㳚|CJK-A|暂时未知|
|6921|U+2C629|𬘩|CJK-E|暂时未知|
|6922|U+2B127|𫄧|CJK-C|暂时未知|
|6959|U+2C0A9|𬂩|CJK-E|暂时未知|
|6967|U+2B806|𫠆|CJK-D|暂时未知|
|6995|U+2B461|𫑡|CJK-C|暂时未知|
|7007|U+2CB39|𬬹|CJK-E|暂时未知|
|7008|U+2CB3F|𬬿|CJK-E|暂时未知|
|7053|U+2C288|𬊈|CJK-E|暂时未知|
|7093|U+2CCFF|𬳿|CJK-E|暂时未知|
|7097|U+2C62B|𬘫|CJK-E|暂时未知|
|7098|U+40AE|䂮|CJK-A|暂时未知|
|7124|U+44EB|䓫|CJK-A|暂时未知|
|7126|U+44EC|䓬|CJK-A|暂时未知|
|7134|U+44DB|䓛|CJK-A|暂时未知|
|7169|U+4383|䎃|CJK-A|暂时未知|
|7177|U+2B4EF|𫓯|CJK-C|暂时未知|
|7198|U+3FE0|㿠|CJK-A|暂时未知|
|7213|U+43F2|䏲|CJK-A|暂时未知|
|7219|U+20164|𠅤|CJK-B|暂时未知|
|7242|U+3944|㥄|CJK-A|暂时未知|
|7249|U+2C907|𬤇|CJK-E|暂时未知|
|7250|U+2B36F|𫍯|CJK-C|暂时未知|
|7254|U+2C90A|𬤊|CJK-E|暂时未知|
|7276|U+2B626|𫘦|CJK-C|暂时未知|
|7278|U+2B7C5|𫟅|CJK-D|暂时未知|
|7279|U+2C62F|𬘯|CJK-E|暂时未知|
|7299|U+2A8FB|𪣻|CJK-C|暂时未知|
|7326|U+2C0CA|𬃊|CJK-E|暂时未知|
|7378|U+2B4F6|𫓶|CJK-C|暂时未知|
|7382|U+2CB4E|𬭎|CJK-E|暂时未知|
|7402|U+4403|䐃|CJK-A|暂时未知|
|7414|U+2BDF7|𫷷|CJK-E|暂时未知|
|7450|U+36F9|㛹|CJK-A|暂时未知|
|7516|U+48D8|䣘|CJK-A|暂时未知|
|7580|U+2B536|𫔶|CJK-C|暂时未知|
|7610|U+2B5B3|𫖳|CJK-C|暂时未知|
|7617|U+2B62A|𫘪|CJK-C|暂时未知|
|7618|U+2B62C|𫘬|CJK-C|暂时未知|
|7654|U+2CE18|𬸘|CJK-E|暂时未知|
|7682|U+2CB64|𬭤|CJK-E|暂时未知|
|7737|U+2C91D|𬤝|CJK-E|暂时未知|
|7747|U+3EEC|㻬|CJK-A|暂时未知|
|7782|U+3807|㠇|CJK-A|暂时未知|
|7789|U+2CB69|𬭩|CJK-E|暂时未知|
|7831|U+2CD0A|𬴊|CJK-E|暂时未知|
|7854|U+2B7E6|𫟦|CJK-D|暂时未知|
|7868|U+3813|㠓|CJK-A|暂时未知|
|7872|U+2CB6C|𬭬|CJK-E|暂时未知|
|7916|U+2B137|𫄷|CJK-C|暂时未知|
|7943|U+2CB78|𬭸|CJK-E|暂时未知|
|7945|U+2CB7C|𬭼|CJK-E|暂时未知|
|7961|U+2CD9F|𬶟|CJK-E|暂时未知|
|8000|U+45F4|䗴|CJK-A|暂时未知|
|8024|U+4396|䎖|CJK-A|暂时未知|
|8032|U+3C00|㰀|CJK-A|暂时未知|
|8064|U+3E0C|㸌|CJK-A|暂时未知|
|8073|U+2C64B|𬙋|CJK-E|暂时未知|

**Comment by kitty-panics** [comment]
补充上述 "暂时未知" 的拼音。

字表序号 | Unicode编码  | 汉字 | 编码区  | 拼音
-- | -- | -- | -- | --
6551 | U+2C8DE | 𬣞 | CJK-E | zhǔ
6594 | U+2BD77 | 𫵷 | CJK-E | lì
6640 | U+2B61C | 𫘜 | CJK-C | wén
6657 | U+48BC  | 䢼 | CJK-A | gōng
6670 | U+2CA02 | 𬨂 | CJK-E | qí
6686 | U+37C3  | 㟃 | CJK-A | sī
6688 | U+2CB29 | 𬬩 | CJK-E | yì
6700 | U+344A  | 㑊 | CJK-A | yì
6730 | U+2B363 | 𫍣 | CJK-C | tóng
6731 | U+2C8F3 | 𬣳 | CJK-E | hěn
6739 | U+2CBC0 | 𬯀 | CJK-E | jī
6744 | U+2BC1B | 𫰛 | CJK-E | xíng
6747 | U+2CCF5 | 𬳵 | CJK-E | pī
6752 | U+2B80A | 𫠊 | CJK-D | xuán
6797 | U+3B55  | 㭕 | CJK-A | qū
6847 | U+2CB31 | 𬬱 | CJK-E | jīn
6848 | U+2CB2D | 𬬭 | CJK-E | lún
6865 | U+43E1  | 䏡 | CJK-A | shì
6867 | U+26676 | 𦙶 | CJK-B | gǔ
6879 | U+3DB2  | 㶲 | CJK-A | yòng
6884 | U+3CDA  | 㳚 | CJK-A | xù
6921 | U+2C629 | 𬘩 | CJK-E | tīng
6922 | U+2B127 | 𫄧 | CJK-C | yán
6959 | U+2C0A9 | 𬂩 | CJK-E | jiā
6967 | U+2B806 | 𫠆 | CJK-D | kuǐ
6995 | U+2B461 | 𫑡 | CJK-C | méng
7007 | U+2CB39 | 𬬹 | CJK-E | shén
7008 | U+2CB3F | 𬬿 | CJK-E | zhāo
7053 | U+2C288 | 𬊈 | CJK-E | xún
7093 | U+2CCFF | 𬳿 | CJK-E | tú
7097 | U+2C62B | 𬘫 | CJK-E | huán
7098 | U+40AE  | 䂮 | CJK-A | lüè
7124 | U+44EB  | 䓫 | CJK-A | qí
7126 | U+44EC  | 䓬 | CJK-A | zhuó
7134 | U+44DB  | 䓛 | CJK-A | qū
7169 | U+4383  | 䎃 | CJK-A | rǎn
7177 | U+2B4EF | 𫓯 | CJK-C | jī
7198 | U+3FE0  | 㿠 | CJK-A | huàng
7213 | U+43F2  | 䏲 | CJK-A | dié
7219 | U+20164 | 𠅤 | CJK-B | xí
7242 | U+3944  | 㥄 | CJK-A | líng
7249 | U+2C907 | 𬤇 | CJK-E | yīn
7250 | U+2B36F | 𫍯 | CJK-C | xián
7254 | U+2C90A | 𬤊 | CJK-E | shì
7276 | U+2B626 | 𫘦 | CJK-C | táo
7278 | U+2B7C5 | 𫟅 | CJK-D | liáng
7279 | U+2C62F | 𬘯 | CJK-E | zhǔn
7299 | U+2A8FB | 𪣻 | CJK-C | lóu
7326 | U+2C0CA | 𬃊 | CJK-E | zhì
7378 | U+2B4F6 | 𫓶 | CJK-C | xuān
7382 | U+2CB4E | 𬭎 | CJK-E | hóng
7402 | U+4403  | 䐃 | CJK-A | jùn
7414 | U+2BDF7 | 𫷷 | CJK-E | xīn
7450 | U+36F9  | 㛹 | CJK-A | pián
7516 | U+48D8  | 䣘 | CJK-A | táng
7580 | U+2B536 | 𫔶 | CJK-C | niè
7610 | U+2B5B3 | 𫖳 | CJK-C | yūn
7617 | U+2B62A | 𫘪 | CJK-C | yuán
7618 | U+2B62C | 𫘬 | CJK-C | xí
7654 | U+2CE18 | 𬸘 | CJK-E | yǎn
7682 | U+2CB64 | 𬭤 | CJK-E | hóu
7737 | U+2C91D | 𬤝 | CJK-E | huì
7747 | U+3EEC  | 㻬 | CJK-A | tū
7782 | U+3807  | 㠇 | CJK-A | jiù
7789 | U+2CB69 | 𬭩 | CJK-E | wēng
7831 | U+2CD0A | 𬴊 | CJK-E | lín
7854 | U+2B7E6 | 𫟦 | CJK-D | suì
7868 | U+3813  | 㠓 | CJK-A | méng
7872 | U+2CB6C | 𬭬 | CJK-E | wèi
7916 | U+2B137 | 𫄷 | CJK-C | yì
7943 | U+2CB78 | 𬭸 | CJK-E | lín
7945 | U+2CB7C | 𬭼 | CJK-E | suì
7961 | U+2CD9F | 𬶟 | CJK-E | là
8000 | U+45F4  | 䗴 | CJK-A | tíng
8024 | U+4396  | 䎖 | CJK-A | zēng
8032 | U+3C00  | 㰀 | CJK-A | lí
8064 | U+3E0C  | 㸌 | CJK-A | huò
8073 | U+2C64B | 𬙋 | CJK-E | xiāng

数据来源：[mozillazg/pinyin-data
](https://github.com/mozillazg/pinyin-data/blob/master/kMandarin_8105.txt)

**Comment by CNMan** [comment]
@Cool-Pan 多谢帮忙：）

**Comment by CNMan** [comment]
剩下这些了，其他的都已收录

|字表序号|Unicode编码|汉字|编码区|拼音|
|------|------|------|------|------|
|6657|U+48BC|䢼|CJK-A|gōng|
|6867|U+26676|𦙶|CJK-B|gǔ|
|7737|U+2C91D|𬤝|CJK-E|huì|
|6959|U+2C0A9|𬂩|CJK-E|jiā|
|7961|U+2CD9F|𬶟|CJK-E|là|
|7488|U+84E2|蓢|CJK|lǎng|
|7846|U+6A51|橑|CJK|lǎo|
|6939|U+73D5|珕|CJK|lì|
|7943|U+2CB78|𬭸|CJK-E|lín|
|8022|U+7FF7|翷|CJK|lín|
|6961|U+68A0|梠|CJK|lǚ|
|7852|U+78DC|磜|CJK|qì|
|6874|U+997B|饻|CJK|xī|
|7441|U+6569|敩|CJK|xiào|
|6970|U+782B|砫|CJK|zhǔ|

**Comment by zgdlime** [comment]
@CNMan 《通用规范汉字表》8105汉字请在https://www.unicode.org/versions/Unicode13.0.0/ 
 中“kTGHZ2013”《通用规范汉字字典》核对
下载https://www.unicode.org/Public/13.0.0/ucd/Unihan-13.0.0d4.zip

**Comment by CNMan** [comment]
@zgdlime 多谢
