### ISSUE TITLE
部分字的拼音前面的序号错误？

### ISSUE THREAD

**Issue by kitty-panics** [CNMan/XDHYCD7th#4]
部分字的拼音前面的序号错误，可能是将 **数字 1** 误打成 **字母 l** （小写）。

例如 "**得**" 字。以下是通过 ``Grep`` 命令检索 XDHYCD7th.txt 文件的结果（只保留汉字和拼音）:

```TXT
【得】ldé
【得】2dé动
【得】•de助
【得】děi
```

应该更正为：

```TXT
【得】1dé
【得】2dé动
【得】•de助
【得】děi
```

另：在 [现代汉语词典（第五版）全文TXT分享](http://bbs.unispim.com/forum.php?mod=viewthread&tid=31657) 中就存在这个问题。

**Comment by CNMan** [comment]
这部分原定在更新计划4时校订
大概有多少行有问题？能否提供列表或grep命令？多谢

**Comment by kitty-panics** [comment]
我是在依据本项目过滤出《通用规范汉字表》中的多音字时意外看见的，所以具体有多少字存在这个问题不太清楚。
